"""cleanup legacy column

Revision ID: 3481bc0ec197
Revises: 7f3624207078
Create Date: 2026-08-31 13:11:53.779257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3481bc0ec197'
down_revision = '7f3624207078'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_payments', schema=None) as batch_op:
        batch_op.alter_column('total_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('amount_received',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('pending_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('amount_paid',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.drop_column('amount_paid_original')

    with op.batch_alter_table('student_results', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)

    with op.batch_alter_table('student_results', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('student_payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount_paid_original', sa.NUMERIC(precision=12, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=False))
        batch_op.alter_column('amount_paid',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=14, scale=2),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('pending_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('amount_received',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('total_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))

    # ### end Alembic commands ###
