"""initial migration

Revision ID: 7f3624207078
Revises: 
Create Date: 2026-08-19 08:15:53.446348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f3624207078'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('playing_with_neon')
    with op.batch_alter_table('student_payments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_student_payments_student'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'students', ['student_id'], ['id'])

    with op.batch_alter_table('student_remarks', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_student_remarks_student'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'students', ['student_id'], ['id'])

    with op.batch_alter_table('student_results', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_student_results_student'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'students', ['student_id'], ['id'])

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('student_type_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('student_type_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('student_results', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_student_results_student'), 'students', ['student_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('student_remarks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_student_remarks_student'), 'students', ['student_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('student_payments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_student_payments_student'), 'students', ['student_id'], ['id'], ondelete='CASCADE')

    op.create_table('playing_with_neon',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('value', sa.REAL(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('playing_with_neon_pkey'))
    )
    # ### end Alembic commands ###